# Generated by Django 4.1.3 on 2022-11-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_dob', models.DateField()),
                ('user_pswd', models.CharField(max_length=50)),
            ],
        ),
    ]
